baseurl = "https://gizmolab.netlify.com/"
#languageCode = "en-us"
defaultContentLanguage = "el"
languageCode = "el-gr"
theme = "terminal"
paginate = 5
copyright = "© copyleft 2022 gizmolab"
title = "Gizmolab"

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"
  keywords = "hacklab, free software, foss, open source, thessaloniki"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "orange"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  oneHeadingSize = false

  # whether to show a page's estimated reading time
  # readingTime = false # default

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  # Toc = false # default

  # set title for the table of contents
  # can be overridden in a page's front-matter
  # TocTitle = "Table of Contents" # default


[languages]
  [languages.el]
    languageName = "Ελληνικά"
    subtitle = "Το gizmolab είναι ένα hack-lab στην Θεσσαλονίκη"
    menuMore = "Περισσότερα"
    readMore = "Διάβασε περισσότερα"
    readOtherPosts = "Άλλες δημοσιεύσεις"
    newerPosts = "Νεότερες δημοσιεύσεις"
    olderPosts = "Παλαιότερες δημοσιεύσεις"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.el.params.logo]
      logoText = "Gizmolab"
      logoHomeLink = "/"

    [languages.el.menu]
      [[languages.el.menu.main]]
        identifier = "about"
        name = "Σχετικά"
        url = "/about"
      [[languages.el.menu.main]]
        identifier = "provoles"
        name = "Προβολές"
        url = "/tags/provoles"
  [languages.en]
    languageName = "English"
    subtitle = "A hacklab based in Thessaloniki"
    owner = "Gizmolab team"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "Gizmolab"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.el.menu.main]]
        identifier = "provoles"
        name = "Movie Shows"
        url = "/tags/provoles"
