baseurl = "https://gizmolab.net/"
#languageCode = "en-us"
defaultContentLanguage = "el"
languageCode = "el-gr"
theme = "terminal"
paginate = 5
copyright = "ğŸ„¯ copyleft 2022 gizmolab"
title = "Gizmolab"
timeZone = "Europe/Athens"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"
  keywords = "hacklab, free software, foss, open source, thessaloniki"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "orange"

  emptySectionMessage = "Î”Ï…ÏƒÏ„Ï…Ï‡ÏÏ‚ Î´ÎµÎ½ Ï…Ï€Î¬ÏÏ‡ÎµÎ¹ ÎºÎ¬Ï„Î¹ Î¼Î­Ï‡ÏÎ¹ ÏƒÏ„Î¹Î³Î¼Î®Ï‚ :("

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5

  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true
  
  # set a custom cover (default is the favicon)
  customCover = "gizmolab-cover.png"

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false

  # set a custom favicon (default is a `themeColor` square)
  favicon = "gizmolab-favicon.ico"
  
  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  oneHeadingSize = false

  # whether to show a page's estimated reading time
  # readingTime = false # default

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  # Toc = false # default

  # set title for the table of contents
  # can be overridden in a page's front-matter
  # TocTitle = "Table of Contents" # default


[languages]
  [languages.el]
    languageName = "Î•Î»Î»Î·Î½Î¹ÎºÎ¬"
    subtitle = "Î¤Î¿ gizmolab ÎµÎ¯Î½Î±Î¹ Î­Î½Î± hack-lab ÏƒÏ„Î·Î½ Î˜ÎµÏƒÏƒÎ±Î»Î¿Î½Î¯ÎºÎ·"
    menuMore = "Î ÎµÏÎ¹ÏƒÏƒÏŒÏ„ÎµÏÎ±"
    readMore = "Î”Î¹Î¬Î²Î±ÏƒÎµ Ï€ÎµÏÎ¹ÏƒÏƒÏŒÏ„ÎµÏÎ±"
    readOtherPosts = "Î†Î»Î»ÎµÏ‚ Î´Î·Î¼Î¿ÏƒÎ¹ÎµÏÏƒÎµÎ¹Ï‚"
    newerPosts = "ÎÎµÏŒÏ„ÎµÏÎµÏ‚ Î´Î·Î¼Î¿ÏƒÎ¹ÎµÏÏƒÎµÎ¹Ï‚"
    olderPosts = "Î Î±Î»Î±Î¹ÏŒÏ„ÎµÏÎµÏ‚ Î´Î·Î¼Î¿ÏƒÎ¹ÎµÏÏƒÎµÎ¹Ï‚"
    missingContentMessage = "Î— ÏƒÎµÎ»Î¯Î´Î± Î´Îµ Î²ÏÎ­Î¸Î·ÎºÎµ..."
    missingBackButtonLabel = "Î Î¯ÏƒÏ‰ ÏƒÏ„Î·Î½ Î±ÏÏ‡Î¹ÎºÎ® ÏƒÎµÎ»Î¯Î´Î±"

    [languages.el.params.logo]
      logoImg = "/gizmolab-logo-small.png"
      logoText = "Gizmolab"
      logoHomeLink = "/"

    [languages.el.menu]
      [[languages.el.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects"
        weight = 1
      [[languages.el.menu.main]]
        identifier = "actions"
        name = "Î”ÏÎ¬ÏƒÎµÎ¹Ï‚"
        url = "/actions"
        weight = 2
      [[languages.el.menu.main]]
        identifier = "ekdiloseis"
        name = "Î•ÎºÎ´Î·Î»ÏÏƒÎµÎ¹Ï‚"
        url = "/events"
        weight = 3
      [[languages.el.menu.main]]
        identifier = "about"
        name = "Î£Ï‡ÎµÏ„Î¹ÎºÎ¬"
        url = "/about"
        weight = 4
      [[languages.el.menu.main]]
        identifier = "contact"
        name = "Î•Ï€Î¹ÎºÎ¿Î¹Î½Ï‰Î½Î¯Î±"
        url = "/contact"
        weight = 5
        
#  [languages.en]
#    languageName = "English"
#    subtitle = "A hacklab based in Thessaloniki"
#    owner = "Gizmolab team"
#    menuMore = "Show more"
#    readMore = "Read more"
#    readOtherPosts = "Read other posts"
#    newerPosts = "Newer posts"
#    olderPosts = "Older posts"
#    missingContentMessage = "Page not found..."
#    missingBackButtonLabel = "Back to home page"

#    [languages.en.params.logo]
#      logoImg = "/gizmolab-logo-small.png"
#      logoText = "Gizmolab"
#      logoHomeLink = "/"

#    [languages.en.menu]
#      [[languages.en.menu.main]]
#        identifier = "about"
#        name = "About"
#        url = "/about"
#      [[languages.el.menu.main]]
#        identifier = "movies"
#        name = "Movie Shows"
#        url = "/tags/provoles"
